# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Clarissa Podell
author: Clarissa Podell
email: clarissapodell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal site to showcase my academic work, side-projects, and interests for personal and professional use.
#baseurl: "https://c1arissa.github.io/minimal" # the subpath of your site, e.g. /blog
baseurl: "/minimal" # the subpath of your site, e.g. /blog
url: "https://c1arissa.github.io/minimal" # the base hostname & protocol for your site
#twitter_username: fareez_ahamed
github_username:  c1arissa
linkedin: clarissapodell
google_analytics: UA-112251458-1 

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
        - "/index.md"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
